### ISSUE TITLE
Discrepancy in documentation and Tool description

### ISSUE THREAD

**Issue by Rohit-Satyam** [bonsai-team/Porechop_ABI#11]
Hi

I observe a small discrepancy in documentation

The tool description says, that `-i` option require either a single fastq file or a directory. But when I provide directory path containing multiple samples fastq files, I get the following error:

>porechop_abi: error: unrecognized arguments: barcode82_sample_10.fastq barcode83_sample_1904.fastq barcode84_sample_1905.fastq barcode85_sample_441.fastq barcode86_sample_4447.fastq

```
Main options:
  -i INPUT, --input INPUT             FASTA/FASTQ of input reads or a directory which will be recursively
                                      searched for FASTQ files (required)
```

Lastly can you see if there is an option `--multi_run` in the tool as documentation says because when using it, I get the error:
>porechop_abi: error: unrecognized arguments: --multi_run 10

or is this replaced by `-nr`/

**Comment by qbonenfant** [comment]
Hi, This issue is finally resolved by PR #15  (sorry it took so long).
I will now close this issue.
Thanks for your contribution to this project.
