### ISSUE TITLE
Fix to make your code work for python3.6

### ISSUE THREAD

**Issue by R1N6MAN** [bonsai-team/Porechop_ABI#13]
You description says that it must use python3.6 or above, however the code fails at 3.6 because of one line of code:
Line 41 on consensus.py  says
capture_output=True,
To make this compatible with 3.6  it should be
stderr=PIPE,stdout=PIPE,

I sent a pull request for the change in a fork.  Please review and let me know as soon as its updated.  Otherwise our code has to maintain this edit in our dev cycle which is complicated to manage.   Thank you!

**Comment by qbonenfant** [comment]
Your pull request has been reviewed.
The problem has been confirmed and your solution should fix it.
I just requested a minor change to avoid issue with futur python versions.

**Comment by qbonenfant** [comment]
The pull requests have been processed.
Thanks for your contribution to this project.
