### ISSUE TITLE
duplicated read names for split reads in fastq with additional tags in name line

### ISSUE THREAD

**Issue by johannesgeibel** [bonsai-team/Porechop_ABI#16]
When Porechop_ABI splits a read due to an adapter within it, it adds "_1", "_2" ... to the end of the read name line, to make them unique again. However, when there are multiple tags in the fastq (e.g. keeping methylation tags - which will be broken afterwards anyway - I know ;) ), the end of the line is not the end of the read name. This then causes problems with duplicated read names later on.

Example:
```
@15296e58-2809-4d12-b468-a4ff0b217bfa   qs:i:11 du:f:46.8908 ... ,229,0,253,253,209,254,253,247,250,252,237,228,62,246_1
...
@15296e58-2809-4d12-b468-a4ff0b217bfa   qs:i:11 du:f:46.8908  ... 229,0,253,253,209,254,253,247,250,252,237,228,62,246_2
```
The problematic code should be in: https://github.com/bonsai-team/Porechop_ABI/blob/d572abbcaaae9ffa08a9d46b8dd03f63507728bc/porechop_abi/nanopore_read.py#L494   

which looks only for `' '`, but not for `"\t"`.

I can open a pull request, if you want me to, but it might be less work for you, if you solve the problem directly.

Thanks,
Johannes

**Comment by johannesgeibel** [comment]
I actually found a small time slot to propose a solution: https://github.com/bonsai-team/Porechop_ABI/pull/17 Hope it helps

**Comment by qbonenfant** [comment]
Hi, thanks for reporting this issue,
I will review it ASAP (hopefully before next week).

**Comment by qbonenfant** [comment]
As i said in the merge request convo, sorry for the delay.
Your merge request has been reviewed and accepted, the change should be available for everyone now.
Thanks again for your contribution, i will now close this issue (as it is solved).
