### ISSUE TITLE
Repository not found in biocontainers

### ISSUE THREAD

**Issue by sofstam** [bonsai-team/Porechop_ABI#6]
Hello, 

I am trying to create an nf-core module for Porechop_ABI https://github.com/nf-core/modules/issues/2325. I get the error `Repository not found` when I try to access porechop_abi with the following link: https://quay.io/repository/biocontainers/porechop_abi.

Could you please help me with that?

**Comment by qbonenfant** [comment]
Hi,
I will try to help you with this issue.
I looked around a bit, and it seems that the docker container for porechop_abi linked on bioconda does not exists, and I'm not exactly sure why.
Porechop_ABI addition on bioconda is quite new, this may be the reason.
I will ask bioconda team if they know better, or encountered related issues in the past.

**Comment by sofstam** [comment]
Hi,

Thanks for your quick reply and looking into that. This is the link I am using: https://bioconda.github.io/recipes/porechop_abi/README.html?highlight=porechop_abi#package-package%20&%23x27;porechop_abi&%23x27

**Comment by qbonenfant** [comment]
Bioconda team has been notified.
It seems the docker image was private, this is why you could not reach it.
They are currently fixing the issue, the link should work any time now.

**Comment by sofstam** [comment]
The docker image is public. Are you planning to add `porechop_abi` to https://depot.galaxyproject.org/singularity/?

**Comment by qbonenfant** [comment]
We may add it at some point, but this is not on our (already quite long) "to do" list for now.
Preparing the repo for conda already took quite some times, and clearly showed some changes in the installation
procedure are needed.

All i can recommand is to check for new release.
I will try to keep a "futur changes" list somewhere (probably in release notes).

As the current issue is resolved, i will close this ticket.
Thanks for your contribution.

**Comment by qbonenfant** [comment]
Well, that's less ressearch and debugging time on my side then, thanks for the tip.

My previous statement still holds, as we really need to update the installation process originally developped by rrwick, upon which we have built our installer.
Despite working well on a lot of platforms, this is not as easy, reliable, and "maintainable" as I would like it to be.
